on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


jobs:
  R-windows-binary:
  
    runs-on: windows-latest
    
    steps:
        - uses: actions/checkout@v2

        - uses: r-lib/actions/setup-r@v2
          with: 
            r-version: "release"
            install-r: true
            update-rtools: true
            rtools-version: "42"

        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::rcmdcheck
            needs: check
            
        - uses: r-lib/actions/setup-tinytex@v2
        
        - name: Install additional LaTeX packages
          run: |
            tlmgr install scrartcl mparhack
        
        - name: Build Binary Package
          shell: cmd
          run: |
            R CMD INSTALL --build --preclean clpAPI
            
        - name: Upload
          uses: actions/upload-artifact@v3
          with:
            name: Windows Binary Package
            path: ${{ github.workspace }}/*.zip