on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Check R Package

jobs:
  R-CMD-check:
  
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
        fail-fast: false
        matrix:
            config:
                - {os: windows-latest, r: 'release', rtools-version: '42'}
                - {os: ubuntu-latest, r: 'release'}
                - {os: macos-latest, r: 'release'}

    steps:
        - name: Install Ubuntu Necessities
          if: matrix.config.os == 'ubuntu-latest'
          run: |
            sudo apt-get update
            sudo apt-get install coinor-libclp-dev texinfo 

        - name: Install macOS Necessities
          if: matrix.config.os == 'macos-latest'
          run: |
            brew install clp pkg-config

        - uses: actions/checkout@v2

        - uses: r-lib/actions/setup-r@v2
          with: 
            r-version: "release"
            install-r: true
            update-rtools: true
            rtools-version: "42"

        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::rcmdcheck
            needs: check
            
        - uses: r-lib/actions/setup-tinytex@v2
        
        - name: Install additional LaTeX packages
          run: |
            tlmgr install grfext

        - uses: r-lib/actions/check-r-package@v2
          with:
            error-on: '"error"'
