on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


jobs:
  R-CMD-check:
  
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
        fail-fast: false
        matrix:
            config:
                - {os: windows-latest, r: 'release', rtools-version: '42'}

    steps:
        - uses: actions/checkout@v2
        - uses: r-lib/actions/setup-r@v2
        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::rcmdcheck
            needs: check
        - uses: r-lib/actions/check-r-package@v2